name: markdown-lint
on:
    push:
        branches:
            - main
env:
    PYTHON_VERSION: '3.12'
    POETRY_VERSION: '1.8.3'
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: DavidAnson/markdownlint-cli2-action@v16
              continue-on-error: true
              with:
                  globs: '**/*.md'
                  config: '.markdownlint-cli2.jsonc'
                  fix: true
            - name: push diff
              run: |
                  git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  if (git diff --shortstat | grep '[0-9]'); then \
                      git add .; \
                      git commit -m "formatted by markdownlint-cli2"; \
                      git push origin HEAD:${GITHUB_REF}; \
                  fi
    update-page-info:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Cache poetry cache
              id: poetry-cache
              uses: actions/cache@v3
              with:
                  path: /home/runner/.local
                  key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-poetry${{ env.POETRY_VERSION }}
            - name: Set a path
              run: |
                  echo "$HOME/.local/bin" >> $GITHUB_PATH
              if: steps.poetry-cache.outputs.cache-hit == 'true'
            - name: Cache packages
              id: packages-cache
              uses: actions/cache@v3
              with:
                  path: /home/runner/.cache/pypoetry
                  key: ${{ runner.os }}-${{ github.job }}-packages-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-${{ github.job }}-packages-
            - name: Setup Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Install poetry
              run: |
                  curl -sSL https://install.python-poetry.org | python3 - --version ${{ env.POETRY_VERSION }}
                  echo "$HOME/.local/bin" >> $GITHUB_PATH
              if: steps.poetry-cache.outputs.cache-hit != 'true'
            - name: Resolve Dependencies
              run: |
                  poetry install
              if: steps.packages-cache.outputs.cache-hit != 'true'
            - name: Run script by Poetry
              run: |
                  poetry run python update_page_info.py
            - name: push diff
              run: |
                  git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  if (git diff --shortstat | grep '[0-9]'); then \
                      git add .; \
                      git commit -m "update page info"; \
                      git pull; \
                      git push origin HEAD:${GITHUB_REF}; \
                  fi
